Fix some build problems
- Fix dependencies in opam file.
- Add missing `-DWLR_USE_UNSTABLE`.

Error was:

    In file included from types_stubgen.c:4:
    /usr/include/wlr/backend.h:6:2: error: #error "Add -DWLR_USE_UNSTABLE to enable unstable wlroots features"
        6 | #error "Add -DWLR_USE_UNSTABLE to enable unstable wlroots features"
          |  ^~~~~

Note: the project still doesn't build, due to other upstream API changes.